# Generated by Django 5.2 on 2025-05-08 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField(max_length=500)),
                ('categoria', models.CharField(max_length=50)),
                ('fabricante', models.CharField(max_length=60)),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tiempo_entrega', models.IntegerField()),
                ('proveedor', models.CharField(max_length=60)),
                ('stock', models.IntegerField()),
            ],
        ),
    ]
